// Embeds agent/system-prompt.md and videos/*.json into lib/embedded.ts so the
// server routes work on filesystem-less hosts (Cloudflare Workers). Runs on prebuild.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const prompt = fs.readFileSync(path.join(ROOT, "agent", "system-prompt.md"), "utf8");
const videos = {};
for (const f of fs.readdirSync(path.join(ROOT, "videos")).filter((f) => f.endsWith(".json"))) {
  videos[f.replace(/\.json$/, "")] = JSON.parse(
    fs.readFileSync(path.join(ROOT, "videos", f), "utf8")
  );
}
fs.writeFileSync(
  path.join(ROOT, "lib", "embedded.ts"),
  `// AUTO-GENERATED by scripts/embed.mjs — do not edit.\n` +
    `export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};\n` +
    `export const EMBEDDED_VIDEOS: Record<string, any> = ${JSON.stringify(videos, null, 2)};\n`
);
console.log(`embedded ${Object.keys(videos).length} videos + system prompt`);
